# .readthedocs.yaml

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

sphinx:
   builder: html
   configuration: doc/source/conf.py
   fail_on_warning: true

python:
  install:
    - requirements: oc_projet13/requirements.txt
    - method: pip
      path: oc_projet13
