services:
  - type: web
    name: oc_lettings_site
    plan: free
    region: frankfurt
    runtime: python
    buildCommand: "./docker-compose-deployment.sh cloud"
    startCommand: "./venv/bin/python -m gunicorn -b :8000 oc_projet13.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
      - fromGroup: oc_projet13
