version: 2.1

orbs:
  python: circleci/python@2.1.1
  browser-tools: circleci/browser-tools@1.2.3

workflows:
  oc_projet13_workflow:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.5
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
<<<<<<< HEAD
        name: Run Tests
        command: |
          ls /home/
          ls /home/circleci/
          /home/circleci/.local/bin/coverage run -m pytest
          /home/circleci/.local/bin/coverage report
          /home/circleci/.local/bin/coverage html
=======
          name: Run Tests
          command: |
            /home/circleci/.local/bin/coverage run -m pytest
            /home/circleci/.local/bin/coverage report
            /home/circleci/.local/bin/coverage html
>>>>>>> 582a3e90b6472dd500a737274cd568034cc07538
      - store_artifacts:
          path: htmlcov

      - run:
          name: Run flake8
          command: flake8
