version: 2.1

orbs:
  python: circleci/python@2.1.1
  browser-tools: circleci/browser-tools@1.2.3

workflows:
  oc_projet13_workflow:
    jobs:
      - build-and-test

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.5
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run Tests
          command: |
            /home/circleci/.local/bin/poetry run coverage -m pytest
            /home/circleci/.local/bin/poetry run coverage report
            /home/circleci/.local/bin/poetry run coverage html
      - store_artifacts:
          path: htmlcov

      - run:
          name: Run flake8
          command: flake8
