version: 2.1

orbs:
  python: circleci/python@2.1.1
  browser-tools: circleci/browser-tools@1.2.3

workflows:
  oc_projet13_workflow:
    jobs:
      - update_coverage
      - build-and-test

jobs:
  update_coverage:
    docker:
      - image: cimg/python:3.10.5
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: ./oc_projet13/requirements.txt
          pkg-manager: pip
      - run:
          name: Run Tests
          command: |
            coverage run -m pytest
            coveralls
  build-and-test:
    docker:
      - image: cimg/python:3.10.5
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run Tests
          command: |
            python -m coverage run -m pytest
            python -m coverage report
            python -m coverage html
      - store_artifacts:
          path: htmlcov

      - run:
          name: Run flake8
          command: flake8
