version: 2.1

orbs:
  python: circleci/python@2.1.1
  browser-tools: circleci/browser-tools@1.2.3
  coveralls: coveralls/coveralls@2.2.1

workflows:
  oc_projet13_workflow:
    jobs:
      - check_coverage
      - build-and-test

jobs:
  check_coverage:
    docker:
      - image: circleci/node:10.0.0
    steps:
      - checkout
      - run:
          command: npm install && make test-coverage
          name: Install and Make
      - coveralls/upload
  build-and-test:
    docker:
      - image: cimg/python:3.10.5
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run Tests
          command: |
            python -m coverage run -m pytest
            python -m coverage report
            python -m coverage html
      - store_artifacts:
          path: htmlcov

      - run:
          name: Run flake8
          command: flake8
