# Generated by Django 3.1.14 on 2023-10-02 15:43

from django.db import migrations

from oc_lettings_site.models import Address, Letting

def migrate_addresses_and_lettings(apps, schema_migration):
    OldAddressModel = apps.get_model("oc_lettings_site", "Address")
    NewAddressModel = apps.get_model("lettings", "Address")
    OldLettingModel = apps.get_model("oc_lettings_site", "Letting")
    NewLettingModel = apps.get_model("lettings", "Letting")

    for old_address in OldAddressModel.objects.all():
        address = NewAddressModel()
        address.number = old_address.number
        address.street = old_address.street
        address.city = old_address.city
        address.state = old_address.state
        address.zip_code = old_address.zip_code
        address.country_iso_code = old_address.country_iso_code
        address.save()

    for old_letting in OldLettingModel.objects.all():
        letting = NewLettingModel()
        letting.title = old_letting.title
        letting.address = NewAddressModel.objects.get(id=old_letting.address.id)
        letting.save()

    OldAddressModel.objects.all().delete()
    OldLettingModel.objects.all().delete()

class Migration(migrations.Migration):
    dependencies = [('oc_lettings_site', '0001_initial'),]
    operations = [migrations.RunPython(migrate_addresses_and_lettings)]
