# Generated by Django 3.1.14 on 2023-10-02 16:59

from django.db import migrations

from oc_lettings_site.models import Profile


def migrate_profiles(apps, schema_migration):
    OldProfileModel = apps.get_model("oc_lettings_site", "Profile")
    NewProfileModel = apps.get_model("profiles", "Profile")

    for old_profile in OldProfileModel.objects.all():
        profile = NewProfileModel()
        profile.user = old_profile.user
        profile.favorite_city = old_profile.favorite_city
        old_profile.delete()
        profile.save()

    OldProfileModel.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [('oc_lettings_site', '0002_auto_20231002_1543'),]
    operations = [migrations.RunPython(migrate_profiles)]
